
version: '3.8'

services:
  example_relational_db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=bobsgames_database
      - MYSQL_USER=bobsgames_admin
      - MYSQL_PASSWORD=bobsgames
      - MYSQL_ROOT_PASSWORD=bobsgames
    ports:
      - '3306:3306'
    volumes: 
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
