
version: '3.8'

services:
  example_relational_db:
    image: mysql:8.0 # postgres:15.2
    restart: always
    environment:
      - MYSQL_DATABASE=bobsgames_database
      - MYSQL_USER=bobsgames_admin
      - MYSQL_PASSWORD=bobsgames
      - MYSQL_ROOT_PASSWORD=bobsgames
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    ports:
      - '3306:3306'
      # - '5432:5432'
    volumes: 
      # - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
